### ISSUE TITLE
Add --limit option

### ISSUE THREAD

**Issue by zhuosun** [adjust/bagger#18]
For cases where we only need handful of lines out of all the logs that we pulled, we want to add a `--limit` option for this.

If `--limit 10` is set, then we output the first 10 log lines and finish the query.

**Comment by roa** [comment]
https://github.com/adjust/bagger/pull/23

merged and deployed. it is a bit different from what you might expect though. it is limiting the results for each subquery generated. so you end up with more results that you might expected.
limiting it to an exact number is not so trivial as it might seems due to implementation details.

tl;dr `--limit 10` limits the amount of results, but you might end up with more results.
